### PR TITLE
Adds PHP 8.4

### PR DESCRIPTION
**Pull request by nickschuch**
https://github.com/phper-framework/phper/issues/162

### CODE REVIEW

**Comment by jmjoy** [comment]
1. You can add `#[allow(static_mut_refs)]` to solve the warning first

    ```
    error: creating a mutable reference to mutable static is discouraged
       --> phper/src/errors.rs:487:31
        |
    487 |                 .push(replace(&mut eg!(exception), null_mut()));
        |                               ^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    ```

2. You can try to add these functions to the blocklist of `phper-sys/build.rs`

    ```
    error: `extern` block uses type `u128`, which is not FFI-safe
        --> /Users/runner/work/phper/phper/target/release/build/phper-sys-2fa65f16eaf39386/out/php_bindings.rs:9760:44
         |
    9760 |     pub fn zend_startup(utility_functions: *mut zend_utility_functions);
         |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
    ```

**Comment by nickschuch** [comment]
Down to zend_random_bytes_insecure. I'm not sure how to handle that.

**Comment by jmjoy** [comment]
Maybe you should block all functions that not FFI-safe.

**Comment by nickschuch** [comment]
I tried zend_random_bytes_insecure but it didn't work. I'm sorry. I'm still quite new to rust.

**Review by jmjoy — APPROVED** [review]

**Pull request merged**
